import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const interDisplay = localFont({
  src: [
    { path: "../../public/fonts/Inter/InterDisplay-Thin.ttf", weight: "100", style: "normal" },
    { path: "../../public/fonts/Inter/InterDisplay-ThinItalic.ttf", weight: "100", style: "italic" },
    { path: "../../public/fonts/Inter/InterDisplay-ExtraLight.ttf", weight: "200", style: "normal" },
    { path: "../../public/fonts/Inter/InterDisplay-ExtraLightItalic.ttf", weight: "200", style: "italic" },
    { path: "../../public/fonts/Inter/InterDisplay-Light.ttf", weight: "300", style: "normal" },
    { path: "../../public/fonts/Inter/InterDisplay-LightItalic.ttf", weight: "300", style: "italic" },
    { path: "../../public/fonts/Inter/InterDisplay-Regular.ttf", weight: "400", style: "normal" },
    { path: "../../public/fonts/Inter/InterDisplay-Italic.ttf", weight: "400", style: "italic" },
    { path: "../../public/fonts/Inter/InterDisplay-Medium.ttf", weight: "500", style: "normal" },
    { path: "../../public/fonts/Inter/InterDisplay-MediumItalic.ttf", weight: "500", style: "italic" },
    { path: "../../public/fonts/Inter/InterDisplay-SemiBold.ttf", weight: "600", style: "normal" },
    { path: "../../public/fonts/Inter/InterDisplay-SemiBoldItalic.ttf", weight: "600", style: "italic" },
    { path: "../../public/fonts/Inter/InterDisplay-Bold.ttf", weight: "700", style: "normal" },
    { path: "../../public/fonts/Inter/InterDisplay-BoldItalic.ttf", weight: "700", style: "italic" },
    { path: "../../public/fonts/Inter/InterDisplay-ExtraBold.ttf", weight: "800", style: "normal" },
    { path: "../../public/fonts/Inter/InterDisplay-ExtraBoldItalic.ttf", weight: "800", style: "italic" },
    { path: "../../public/fonts/Inter/InterDisplay-Black.ttf", weight: "900", style: "normal" },
    { path: "../../public/fonts/Inter/InterDisplay-BlackItalic.ttf", weight: "900", style: "italic" },
  ],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${interDisplay.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
